version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pongdb
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: pongpassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://ponguser:pongpassword@db:5432/pongdb
      - DEBUG=1  # Set to 0 in production

volumes:
  postgres_data:
