version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - transcendance_network

  web:
    build: ./django
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn transcendance.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/code
      - static_volume:/usr/share/nginx/static
      - ./django/frontend/media:/usr/share/nginx/media  # Correct path for media files
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
    networks:
      - transcendance_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/share/nginx/static
      - ./django/frontend/media:/usr/share/nginx/media  # Correct path for media files
    depends_on:
      - web
    networks:
      - transcendance_network

volumes:
  postgres_data:
  static_volume:

networks:
  transcendance_network:
    driver: bridge
