# Generated by Django 4.2.15 on 2024-08-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='position_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='position_y',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='velocity_x',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='velocity_y',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='paddle',
            name='position',
            field=models.FloatField(default=50.0),
        ),
    ]
